import { Product } from './types';

export const CATEGORIES = [
  "All Categories",
  "Computers and Accessories",
  "Phones and Tablets",
  "Electronics",
  "Fashion",
  "Home and Kitchen",
  "Baby, Kids and Toys",
  "Beauty, Health & Personal Care"
];

export const MOCK_PRODUCTS: Product[] = [
  // --- PHONES AND TABLETS ---
  {
    id: '1',
    name: 'Infinix Note 30 Pro',
    price: 265000,
    category: 'Phones and Tablets',
    image: 'https://picsum.photos/seed/phone1/500/500',
    rating: 4.8,
    reviews: 124,
    shortDescription: 'All-Round FastCharge, 120Hz AMOLED Display.',
    isBestSeller: true
  },
  {
    id: '101',
    name: 'Samsung Galaxy A54 5G',
    price: 450000,
    category: 'Phones and Tablets',
    image: 'https://picsum.photos/seed/galaxy/500/500',
    rating: 4.7,
    reviews: 85,
    shortDescription: 'Awesome camera, long lasting battery, 5G speed.',
  },
  {
    id: '102',
    name: 'Apple iPad 9th Gen',
    price: 380000,
    category: 'Phones and Tablets',
    image: 'https://picsum.photos/seed/ipad/500/500',
    rating: 4.9,
    reviews: 200,
    shortDescription: 'Powerful A13 Bionic chip, 10.2-inch Retina display.',
  },
  {
    id: '103',
    name: 'Tecno Spark 10 Pro',
    price: 105000,
    category: 'Phones and Tablets',
    image: 'https://picsum.photos/seed/tecno/500/500',
    rating: 4.5,
    reviews: 300,
    shortDescription: '32MP Glowing Selfie, G88 Gaming Processor.',
    isBestSeller: true
  },
  {
    id: '104',
    name: 'New Age Power Bank 22500mAh',
    price: 18500,
    category: 'Phones and Tablets',
    image: 'https://picsum.photos/seed/powerbank/500/500',
    rating: 4.8,
    reviews: 890,
    shortDescription: 'Fast charging, durable battery life for travel.',
  },

  // --- COMPUTERS AND ACCESSORIES ---
  {
    id: '7',
    name: 'HP Pavilion 15 Laptop',
    price: 450000,
    category: 'Computers and Accessories',
    image: 'https://picsum.photos/seed/laptop/500/500',
    rating: 4.8,
    reviews: 55,
    shortDescription: 'Core i5, 16GB RAM, 512GB SSD, Backlit Keyboard.',
    isBestSeller: true
  },
  {
    id: '201',
    name: 'Logitech Wireless Mouse M185',
    price: 8500,
    category: 'Computers and Accessories',
    image: 'https://picsum.photos/seed/mouse/500/500',
    rating: 4.5,
    reviews: 320,
    shortDescription: 'Plug-and-play wireless connectivity, 1-year battery life.',
  },
  {
    id: '202',
    name: 'Seagate 1TB External Hard Drive',
    price: 45000,
    category: 'Computers and Accessories',
    image: 'https://picsum.photos/seed/hdd/500/500',
    rating: 4.6,
    reviews: 150,
    shortDescription: 'Portable storage for your photos, movies, and music.',
  },
  {
    id: '203',
    name: 'MacBook Air M2',
    price: 1200000,
    category: 'Computers and Accessories',
    image: 'https://picsum.photos/seed/macbook/500/500',
    rating: 4.9,
    reviews: 40,
    shortDescription: 'Supercharged by M2 chip, 13.6-inch Liquid Retina display.',
  },
  {
    id: '204',
    name: 'Canon Pixma All-in-One Printer',
    price: 65000,
    category: 'Computers and Accessories',
    image: 'https://picsum.photos/seed/printer/500/500',
    rating: 4.3,
    reviews: 110,
    shortDescription: 'Print, copy, scan. Wireless connectivity.',
  },

  // --- ELECTRONICS ---
  {
    id: '3',
    name: 'Oraimo FreePods 4',
    price: 28500,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/pods1/500/500',
    rating: 4.9,
    reviews: 1200,
    shortDescription: 'Active Noise Cancellation, 35.5-hour battery life.',
    isBestSeller: true
  },
  {
    id: '301',
    name: 'Hisense 43" Smart TV',
    price: 220000,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/tv/500/500',
    rating: 4.4,
    reviews: 98,
    shortDescription: 'Full HD, Netflix, YouTube, clear sound.',
  },
  {
    id: '302',
    name: 'JBL Flip 6 Bluetooth Speaker',
    price: 85000,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/speaker/500/500',
    rating: 4.8,
    reviews: 210,
    shortDescription: 'Bold sound, waterproof, dustproof, 12 hours playtime.',
  },
  {
    id: '303',
    name: 'Binatone Industrial Fan',
    price: 45000,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/fan/500/500',
    rating: 4.7,
    reviews: 150,
    shortDescription: 'High efficiency blades, sturdy base.',
  },
  {
    id: '304',
    name: 'Generic 18-inch Ring Light',
    price: 25000,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/ringlight/500/500',
    rating: 4.4,
    reviews: 200,
    shortDescription: 'Perfect for content creation, includes tripod stand.',
  },

  // --- FASHION ---
  {
    id: '2',
    name: 'Ankara Shift Dress (Adire Style)',
    price: 15000,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/ankara1/500/500',
    rating: 4.5,
    reviews: 89,
    shortDescription: 'Hand-dyed Adire cotton fabric, perfect for casual Fridays.',
    isNew: true
  },
  {
    id: '6',
    name: 'Senator Wear (Men\'s Native)',
    price: 25000,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/senator/500/500',
    rating: 4.3,
    reviews: 30,
    shortDescription: 'Premium wool material, tailored fit for owambe.',
    isNew: true
  },
  {
    id: '401',
    name: 'Men\'s Leather Loafers',
    price: 35000,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/shoes/500/500',
    rating: 4.2,
    reviews: 45,
    shortDescription: 'Classic black leather loafers, comfortable for office wear.',
  },
  {
    id: '402',
    name: 'Bone Straight Human Hair Wig',
    price: 150000,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/wig/500/500',
    rating: 4.9,
    reviews: 120,
    shortDescription: 'Double drawn, silky straight, 22 inches.',
    isBestSeller: true
  },
  {
    id: '403',
    name: 'Men\'s Corporate Suit (Navy Blue)',
    price: 65000,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/suit/500/500',
    rating: 4.5,
    reviews: 45,
    shortDescription: 'Slim fit, premium fabric, ideal for office and weddings.',
  },

  // --- HOME AND KITCHEN ---
  {
    id: '5',
    name: 'Scanfrost Gas Cooker (4 Burner)',
    price: 180000,
    category: 'Home and Kitchen',
    image: 'https://picsum.photos/seed/cooker/500/500',
    rating: 4.6,
    reviews: 210,
    shortDescription: 'Stainless steel finish, auto-ignition, durable oven.',
  },
  {
    id: '8',
    name: 'Super Vio Generator 2.5KVA',
    price: 350000,
    category: 'Home and Kitchen',
    image: 'https://picsum.photos/seed/gen/500/500',
    rating: 4.2,
    reviews: 15,
    shortDescription: 'Rugged copper coil generator for constant power.',
  },
  {
    id: '501',
    name: 'Binatone Blender/Grinder',
    price: 25000,
    category: 'Home and Kitchen',
    image: 'https://picsum.photos/seed/blender/500/500',
    rating: 4.5,
    reviews: 300,
    shortDescription: 'Unbreakable jug, powerful motor for smoothies and soups.',
  },
  {
    id: '502',
    name: 'Silver Crest Air Fryer (6L)',
    price: 35000,
    category: 'Home and Kitchen',
    image: 'https://picsum.photos/seed/airfryer/500/500',
    rating: 4.6,
    reviews: 500,
    shortDescription: 'Oil-free cooking, digital touch screen.',
    isBestSeller: true
  },
  {
    id: '503',
    name: 'Qasa Rechargeable Fan 18"',
    price: 55000,
    category: 'Home and Kitchen',
    image: 'https://picsum.photos/seed/qasa/500/500',
    rating: 4.8,
    reviews: 320,
    shortDescription: 'Long lasting battery, remote control included.',
  },

  // --- BEAUTY, HEALTH & PERSONAL CARE ---
  {
    id: '4',
    name: 'Shea Butter (Raw, Unrefined)',
    price: 3500,
    category: 'Beauty, Health & Personal Care',
    image: 'https://picsum.photos/seed/shea1/500/500',
    rating: 4.7,
    reviews: 45,
    shortDescription: '100% natural shea butter from Ogbomosho.',
  },
  {
    id: '601',
    name: 'Nivea Perfect & Radiant Lotion',
    price: 4500,
    category: 'Beauty, Health & Personal Care',
    image: 'https://picsum.photos/seed/lotion/500/500',
    rating: 4.8,
    reviews: 500,
    shortDescription: 'Even tone lotion for radiant skin.',
    isBestSeller: true
  },
  {
    id: '602',
    name: 'Oral-B Electric Toothbrush',
    price: 18000,
    category: 'Beauty, Health & Personal Care',
    image: 'https://picsum.photos/seed/brush/500/500',
    rating: 4.6,
    reviews: 120,
    shortDescription: 'Superior cleaning action compared to regular brushes.',
  },
  {
    id: '603',
    name: 'CeraVe Foaming Facial Cleanser',
    price: 12500,
    category: 'Beauty, Health & Personal Care',
    image: 'https://picsum.photos/seed/cerave/500/500',
    rating: 4.9,
    reviews: 210,
    shortDescription: 'For normal to oily skin, essential ceramides.',
  },

  // --- BABY, KIDS AND TOYS ---
  {
    id: '701',
    name: 'Pampers Baby Dry (Size 3)',
    price: 8500,
    category: 'Baby, Kids and Toys',
    image: 'https://picsum.photos/seed/diapers/500/500',
    rating: 4.9,
    reviews: 1000,
    shortDescription: 'Keeps baby dry for up to 12 hours.',
    isBestSeller: true
  },
  {
    id: '702',
    name: 'Educational Kids Tablet',
    price: 22000,
    category: 'Baby, Kids and Toys',
    image: 'https://picsum.photos/seed/kidstablet/500/500',
    rating: 4.1,
    reviews: 60,
    shortDescription: 'Pre-loaded with educational apps and games.',
  },
  {
    id: '703',
    name: 'Lego Classic Brick Set',
    price: 15000,
    category: 'Baby, Kids and Toys',
    image: 'https://picsum.photos/seed/lego/500/500',
    rating: 4.8,
    reviews: 90,
    shortDescription: 'Creative building blocks for imaginative play.',
  },
  {
    id: '704',
    name: 'Kids Bicycle (Size 16)',
    price: 45000,
    category: 'Baby, Kids and Toys',
    image: 'https://picsum.photos/seed/bike/500/500',
    rating: 4.7,
    reviews: 65,
    shortDescription: 'Comes with training wheels and basket.',
  }
];
